### PR TITLE
Build: Print version (hash) tag whenever app starts

### PR DESCRIPTION
**Pull request by Cahb**
Sample output:
```console
docker logs openlan_cgw 
[2024-07-01T09:55:30Z INFO  ucentral_cgw] Starting CGW application, rev tag: 5149edb
[2024-07-01T09:55:30Z INFO  ucentral_cgw] (1048576, 1048576)
[2024-07-01T09:55:30Z INFO  ucentral_cgw] (1048576, 1048576)
```
...
```console
docker logs openlan_cgw 
[2024-07-01T09:58:01Z INFO  ucentral_cgw] Starting CGW application, rev tag: 5149edb-dirty
[2024-07-01T09:58:01Z INFO  ucentral_cgw] (1048576, 1048576)
[2024-07-01T09:58:01Z INFO  ucentral_cgw] (1048576, 1048576)
```

### CODE REVIEW

**Comment by Cahb** [comment]
Don't mind the pushes;
Just poking around the github actions to find the right flow;

**Comment by Cahb** [comment]
@carsten989 i've added you to the reviewer list to only address the issue i'm having with CI integration: it seems like i cannot simply pass <build-args> for docker action, as this action is included furthermore the action hierarchy;

Please note, that this PR currently doesn't work OK with CI, so it's not to be merged yet;

**Comment by carsten989** [comment]
So it looks like setting CGW_WSS_THREAD_NUM is no longer supported?
I would have taken care of the CI part of this at least on that side, but thanks!
Please also take a look at https://reproducible-builds.org/docs/source-date-epoch/
See the Dockerfile part. Just adding ARG SOURCE_DATE_EPOCH high up in the target copying portion, should allow you to reference that env var.

**Comment by Cahb** [comment]
@carsten989 
> So it looks like setting CGW_WSS_THREAD_NUM is no longer supported?
The confusion basically comes from the following:
Code uses the DEFAULT_WSS_THREAD_NUM:
191         let wss_t_num: usize = match env::var("DEFAULT_WSS_THREAD_NUM") {        

The script we used to run deployment manually through the make run actually pointed to <wrong> enviroment variable:
-       -e CGW_WSS_THREAD_NUM      \
So i changed it to export right env:
+       -e DEFAULT_WSS_THREAD_NUM  \

(Because application expects exact name);

The pod config should be the same, i've just check it's the <DEFAULT_WSS_THREAD_NUM=8> env var that gets exported;

Or are you using the helper script as well, sorry? Did i brake your deployment?

**Comment by Cahb** [comment]
> I would have taken care of the CI part of this at least on that side, but thanks!
Please also take a look at https://reproducible-builds.org/docs/source-date-epoch/
See the Dockerfile part. Just adding ARG SOURCE_DATE_EPOCH high up in the target copying portion, should allow you to reference that env var.
So, the problem is the changes in this pr still do not work and i think the doc you're referencing is purely for TS, righ?
Because i'd love to see the hash inside the CGW app;

**Comment by Cahb** [comment]
@carsten989 maybe we can jump into slack to discuss / find a potential fix or way-to-go for this issue (the docker build-args one)?

**Pull request merged**
